In [1]:
import numpy as np


In [7]:
solution=np.random.randint(0,7,size=5)
def superhirn(answer,status):
    
    status=True
    
    while status==True:
    
        #Randomly choosing a solution for the game
    
        state=np.zeros(len(solution))
        reward_list=[]

    
    
    
        #In order to get the answer that a number is right but the position is wrong i define two lists where
        #the numbers get saved temporary in order to calculate the intersect
        t_state=[]
        t_solution=[]
    
    
        for i in range(len(solution)):
                 
                state[i]=answer[i]
            
                if np.array_equal(state[i],solution[i])==True:
                    reward_list.append(2)
            
                else:
                    t_state.append(state[i])
                    t_solution.append(solution[i])
            
                    t_state_array=np.array(t_state)
                    t_solution_array=np.array(t_solution)
        #Saving the intersect in an array which consists of all the "colors" which are in the solution but are not at the right position
        color_right=np.intersect1d(t_state_array,t_solution_array)
        for n in range(len(color_right)):
            reward_list.append(1)
        for f in range(5-len(color_right)):
            reward_list.append(0)
        reward_vector=np.array(reward_list)       
    
    
        reward=np.array([[np.sum(reward_vector,axis=0)],[np.mean(reward_vector,axis=0)],[np.std(reward_vector,axis=0)]]).reshape(3,1)
        
        return state,reward_vector
    

In [11]:

superhirn(np.array([8,1,3,5,7,]),True)

(array([8., 1., 3., 5., 7.]), array([2, 0, 0, 0, 0, 0]))

In [12]:
print(solution)

[1 1 4 1 1]


In [ ]:
black=1
white=2
yellow=3
orange=4
green=5
blue=6
brown=7
red=8

In [4]:
def game(x,number_of_attempts):
    
    attempt=1
    while attempt<=12:
        
        for i in range(number_of_attempts):
            attempt+=1
            
        
        
        return 

In [5]:
def naive_sum_reward_agent(env, num_episodes=500):
    # this is the table that will hold our summated rewards for
    # each action in each state
    r_table = np.zeros((5, 2))
    for g in range(num_episodes):
        s = env.reset()
        done = False
        while not done:
            if np.sum(r_table[s, :]) == 0:
                # make a random selection of actions
                a = np.random.randint(0, 2)
            else:
                # select the action with highest cummulative reward
                a = np.argmax(r_table[s, :])
            new_s, r, done, _ = env.step(a)
            r_table[s, a] += r
            s = new_s
    return r_table

In [83]:
a=np.array([[1,2],[2,3],[4,5]])
print(a)

[[1 2]
 [2 3]
 [4 5]]


In [82]:
a[1,1]

3